### ISSUE TITLE
Modules not loaded in the release version

### ISSUE THREAD

**Issue by mario6714** [JingMatrix/LSPatch#10]
### Steps to reproduce/复现步骤

1. Open the app Netease
1. 
1. 

### Expected behaviour/预期行为

See the module inside in the app

### Actual behaviour/实际行为

wont show the module inside the app

### Xposed Module List/Xposed 模块列表

```Shell
com.raincat.dolby_beta
```

### LSPatch version/LSPatch 版本

7093

### Android version/Android 版本

14

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
# Replace this line with the log / 将此行用日志替换
```
</details>
[logcat.txt](https://github.com/user-attachments/files/17004714/logcat.txt)

**Comment by JingMatrix** [comment]
If you don't speak English well, you may upload a video to show the issues. I don't understand clearly what you mean.

**Comment by JingMatrix** [comment]
Did you actually enable the module?

**Comment by JingMatrix** [comment]
I meant enable the module from **the LSPatch manager**.

**Comment by JingMatrix** [comment]
How do you patch the NetEase apk? You should do the patch of the original APK inside the manager and enable modules for the patch APK.
I guess that you **didn't re-patch** the original APK when you switched to the release version.

**Comment by JingMatrix** [comment]
> LsPatch > unpatched apk > local > module for the apk > patch > install> open the app > no module in the app

Then you need to long press the patched APK and enable the module for it.

**Comment by JingMatrix** [comment]
As a test, try the local option and enable the module using LSPatch.

**Comment by JingMatrix** [comment]
Could you please follow my advice?
And then **enable the module from the context menu of LSPatch**

**Comment by JingMatrix** [comment]
Please show me a video how that happens.

**Comment by JingMatrix** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/32179719/367565876-e9e8ab1f-bdd8-458f-835f-2b338653cfcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODU1NDEsIm5iZiI6MTcyNjM4NTI0MSwicGF0aCI6Ii8zMjE3OTcxOS8zNjc1NjU4NzYtZTllOGFiMWYtYmRkOC00NThmLTgzNWYtMmIzMzg2NTNjZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA3MjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYjY1NDJiOTM2MzdiOGMzZTlhODYwM2I3ODc1MGM3NTE4ODhhZmFlOGM5ZGQ5OTllNWJiOTBjMDEzNmMyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nnRFCv9OvnUbE-qbZkRObfrZstTQ9cIX5aV8--eijjk)

So the module is selected each time you open the setting ?
App crashed because that no module is enabled.

**Comment by JingMatrix** [comment]
Please record the logs when the crash happens.

**Comment by JingMatrix** [comment]
In case that it is a bug of GitHub Actions, you may try my local build of release version: 
[release_local.zip](https://github.com/user-attachments/files/17005008/release_local.zip)

**Comment by JingMatrix** [comment]
Okay, simply keep using the debug version.
The debug version basically only enable logs and didn't compress the APK.
Without relevant logs, I cannot help this problem.

**Comment by JingMatrix** [comment]
Use the following command for relevant logs:
```
adb logcat -s AndroidRuntime LSPatch LSPosed LSPatch-MetaLoader LSPatch-SigBypass LSPosed-Bridge LSPlant LSPosedContext zygisk64 LSPlt Dobby LSPosedService '*:F'
```

Ensure that you restart the app while recording the log.

**Comment by JingMatrix** [comment]
Thanks, that is relevant logs. Will try to fix it soon.

**Comment by JingMatrix** [comment]
Please don't extract (filter) logs. And save logs into file, don't simply post them in your comments.

**Comment by JingMatrix** [comment]
try this command
```
adb logcat -s AndroidRuntime LSPatch LSPosed LSPatch-MetaLoader LSPatch-SigBypass LSPosed-Bridge LSPlant LSPosedContext zygisk64 LSPlt Dobby LSPosedService '*:F' > filtred_logs.txt
```
It will save logs into `filtred_logs.txt`.

**Comment by JingMatrix** [comment]
Use the following commad
```
adb pull /data/app/~~EtOxLeioLUvIG78PyfgRtA==/com.netease.cloudmusic-oW0WX0uyeAGTU5wa4vuYPA==/base.apk
```
to get a file named `base.apk` and upload it.
In case that you cannot upload it here, send to me by email: jingmatrix@gmail.com

**Comment by JingMatrix** [comment]
This is not a bug of LSPatch. The module doesn't load because `Netease Music` use similar classname obfuscation as the **release** version of LSPatch, which cause a classname conflict finally.

Hence, for`Netease Music`, you **have to** use the debug version of LSPatch since it doesn't have classname obfuscation.

**Comment by JingMatrix** [comment]
Okay, send to me the original APK you patched by email: [jingmatrix@gmail.com](mailto:jingmatrix@gmail.com)

I may verify it.

**Comment by JingMatrix** [comment]
Bug confirmed, will fix it soon.

**Comment by JingMatrix** [comment]
Nope, I checked it.
I was wrong claiming that this is a bug of LSPatch few minutes ago, which was due to that you **sent a patched APK* * instead of an original one.
Later I download an original APK from Netease, and it is exactly as I explained before.

There are not only changes in your system update, many other things changed too, such as that Netease has updated maybe.

**Comment by JingMatrix** [comment]
> a patched one? in that apk someone remove the protection because you cant use the last version netease and lspatch together

I see, they may have used LSPatch once to bypass it.

**Comment by JingMatrix** [comment]
> > > a patched one? in that apk someone remove the protection because you cant use the last version netease and lspatch together
> > 
> > 
> > I see, they may have used LSPatch once to bypass it.
> 
> No, it is another way, I don't know the method

It is irrevlevant, but if you are curious, they used https://github.com/L-JINBIN/ApkSignatureKillerEx

**Comment by JingMatrix** [comment]
> No idea how that person remove that protection but after that i can use without problems but that is before the google play system, after that i found your fork and discover if a use your debug release for the app work but somehow the release version is not working

Because I used more classname obfuscation in my fork (than the original one) out of many considerations.

Currently, Android R8 obfuscation is not so accurate that I can build a release that works with NetEase Music without **breaking some other feature**.
These are considerations from a developper's perspective, things cannot be perfect at current stage.

**Comment by JingMatrix** [comment]
> do you do this?

Yes, explaining details out of LSPatch is not I am willing to do here.

**Comment by JingMatrix** [comment]
> but before that it worked without problems, i found your fork because the old one i used stop working after that update

Yes, I solved this specific problem related to your system update.
Now simply listen to my advices, use the debug version.

**Comment by JingMatrix** [comment]
> wow, i just explain why you can't use the latest version, the apk i share is one that someone remove that protection, if you want use another version you can use a old version of netease like 7.3.30

Thank you for the information but last warning, this is off-topic.
If I have time in the future, I may consider improve LSPatch by taking some inspirations from https://github.com/L-JINBIN/ApkSignatureKillerEx, which is how the protection is removed in the app you sent.

**Comment by JingMatrix** [comment]
> I am going to keep using the debug, i hope your new release in the future fix the problems

It depneds on the Google team, if one day they will do a better job in this: https://developer.android.com/build/shrink-code

**Comment by JingMatrix** [comment]
> Do you recommend use that uninstall?

Better not, some security updates are included as well.
I would rather recommad that you unlock your phone and start using LSPosed.

**Comment by JingMatrix** [comment]
The latest release build should work well for you: https://github.com/JingMatrix/LSPatch/actions/runs/10888848425

**Comment by JingMatrix** [comment]
I simply changed the obfuscation rule.

**Comment by JingMatrix** [comment]
Sure, ask it properly and respect the community.

**Comment by mario6714** [comment]
> > The latest release build should work well for you: https://github.com/JingMatrix/LSPatch/actions/runs/10888848425
> 
> testing, thanks

Hi @JingMatrix , can you share one more time this file please? thanks

**Comment by JingMatrix** [comment]
@mario6714 Simply update your LSPatch to v1.2

**Comment by mario6714** [comment]
> [@mario6714](https://github.com/mario6714) Simply update your LSPatch to v1.2

Not working
