### ISSUE TITLE
[Feature Request] Something regarding Lspatch

### ISSUE THREAD

**Issue by kamharry** [JingMatrix/LSPatch#14]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Problem of Snapenhance feature which stopped working as i sent mail about this

### Describe the solution you'd like/描述你想要的解决方案

Maybe u can try out that and have a look on the root cause ?

**Comment by JingMatrix** [comment]
Please re-submit as a bug, and add information following the template of bug issues.
