### ISSUE TITLE
Crash on Android 13 [Bug] 

### ISSUE THREAD

**Issue by morocoeltopo** [JingMatrix/LSPatch#4]
### Steps to reproduce/复现步骤

1.  Open the manager, it opens without issue
2. Go to manage tab to see installed apps and modules
3. The app freezes and crash, opening it again doesn't solve the issue

Last working version is 0.6 414

### Expected behaviour/预期行为

Open and manage modules and applications normally

### Actual behaviour/实际行为

On release version crashes when opening manage tab

On debug version the tab opens without crashing, the touchscreen works lagged and updating loader gives this error on patched soul browser:
java.io.FileNotFoundException: /data/app/~~oTRe5UUQlMCJLvvoKWZn4w==/com.mycompany.app.soulbrowser-MXYtgTO57w41xI-ZajV1oQ==/base.apk (No such file or directory)

### Xposed Module List/Xposed 模块列表

```Shell
Lspatch
Lucky Patcher
Smartspacer
```

### LSPatch version/LSPatch 版本

0.6 418

### Android version/Android 版本

Android 13

### Shizuku version/Shizuku 版本

versión 13.5.4.r1056.e43ce65

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Apk file/Apk 文件

[Soul v1.4.28.zip](https://github.com/user-attachments/files/16483263/Soul.v1.4.28.zip)

### Logs/日志

I provide two log files, first for release version and second for debug.

[release.zip](https://github.com/user-attachments/files/16483266/release.zip)
[debug.zip](https://github.com/user-attachments/files/16483267/debug.zip)

**Comment by JingMatrix** [comment]
Thanks for reporting the bug of the release version, it is fixed now.
As for the bug in the debug version, I cannot reproduce it. When you patch your app, please ensure that you are patching an APK that isn't patched before.
The apk you upload is already patched before, which might cause the error you reported.

**Comment by JingMatrix** [comment]
> Is because they don't publish apk version anymore, only xapk, or apkm versions, so I need to unsplit it with Apktool to make it possible the patching with LSPatch.

You don't need to unsplit it at all.
Please simply install the orginal app (using Play Store is the easiest way) into your device, and use LSPatch for installed applications.

**Comment by JingMatrix** [comment]
I see it.
Thanks for mentioning this inconvience of surely losing installed scripts with the manager app  when dealing with **split** APKs.
But it seems people can still find unsplit APK installation package, for example [this download page](https://soul-browser.fr.uptodown.com/android/telecharger).
